services:
  server:
    image: w5-chat-server:latest
    ports:
      - 3000:80
    environment:
      - DB_URL=file:/app/db/local.db
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./db:/app/db
