name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/w5-chat-server:latest .
          docker tag ghcr.io/${{ github.repository_owner }}/w5-chat-server:latest ghcr.io/${{ github.repository_owner }}/w5-chat-server:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/w5-chat-server:latest
          docker push ghcr.io/${{ github.repository_owner }}/w5-chat-server:${{ github.sha }}
